apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backend.full-name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "backend.full-name" . }}
  template:
    metadata:
      labels:
        app: {{ include "backend.full-name" . }}
    spec:
      containers:
        - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: Always
          name: backend
          ports:
            - name: backend
              containerPort: 3000
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-{{ .Chart.Name }}-secret
                  key: mongodb-uri