apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend.full-name" . }}-secret
data:
  mongodb-uri: {{with .Values.secret.mongodb_uri -}}
  {{- list "mongodb://" .username ":" .password "@" $.Release.Name "-" .dbchart ":" .dbport "/" .dbconn | join "" | b64enc | quote }}
  {{- end }}
