apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "database.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "database.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "database.fullname" . }}
    spec:
      containers:
        - image: {{ .Values.image.repository }}
          env:
            - name: MONGO_INITDB_DATABASE
              value: guestbook
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-{{ .Chart.Name }}-secret
                  key: mongodb-username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-{{ .Chart.Name }}-secret
                  key: mongodb-password
          name: mongodb
          ports:
            - name: mongodb
              containerPort: 27017
          volumeMounts:
            - name: {{ include "database.fullname" . }}-volume
              mountPath: /data/db
      volumes:
        - name: {{ include "database.fullname" . }}-volume
          persistentVolumeClaim:
            claimName: {{ include "database.fullname" . }}-pvc